# Generated by Django 4.1 on 2022-09-22 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='official_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='comment',
        ),
        migrations.AlterField(
            model_name='payment',
            name='employee_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='salary.employee'),
        ),
    ]
