# Generated by Django 4.1 on 2022-09-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_alter_client_city_alter_client_is_still_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='outcome',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_still_client',
            field=models.BooleanField(default=True),
        ),
    ]
