# Generated by Django 4.1 on 2022-09-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_alter_cash_outcome_alter_client_is_still_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='outcome',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
