# Generated by Django 4.1 on 2022-09-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0007_alter_cash_outcome_alter_employee_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
