# Generated by Django 4.1 on 2022-10-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0008_alter_employee_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_time',
            field=models.DateField(),
        ),
    ]
