# Generated by Django 4.1 on 2022-10-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0010_alter_cash_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
