# Generated by Django 4.1 on 2022-10-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0011_payment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='outcome',
        ),
    ]
