# Generated by Django 4.1 on 2022-10-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0012_remove_cash_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_still_client',
            field=models.CharField(choices=[('Работаем', 'Работаем'), ('Не работаем', 'Не работаем'), ('Непонятно', 'Непонятно')], max_length=40),
        ),
    ]
