# Generated by Django 4.1.3 on 2022-11-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0013_alter_client_is_still_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='motivation_type',
            field=models.CharField(blank=True, choices=[('Старая', 'Старая'), ('Новая', 'Новая')], default=('Новая', 'Новая'), max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.CharField(blank=True, default='Выплата с поступления', max_length=200, null=True),
        ),
    ]
