# Generated by Django 4.1.3 on 2022-11-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0014_employee_motivation_type_alter_payment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='income_item',
            field=models.CharField(choices=[('--КУ Стартап--', 'КУ Стартап'), ('--КУ Бизнес--', 'КУ Бизнес'), ('--КУ Мероприятия--', 'КУ Мероприятия'), ('Другое', 'Другое')], max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='motivation_type',
            field=models.CharField(blank=True, choices=[('Старая', 'Старая'), ('Новая', 'Новая')], default='Новая', max_length=40, null=True),
        ),
    ]
