# Generated by Django 4.1.3 on 2022-11-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0015_alter_cash_income_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='payment_to',
        ),
    ]
