# Generated by Django 4.1.3 on 2022-11-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0017_payment_link_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
