# Generated by Django 4.1.3 on 2022-11-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0018_alter_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
