# Generated by Django 4.1.3 on 2022-11-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0019_alter_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='status',
            field=models.CharField(choices=[('Распределить', 'Распределить'), ('Оплачено сотрудникам', 'Оплачено сотрудникам')], default='Распределить', max_length=40),
        ),
        migrations.AlterField(
            model_name='cash',
            name='income_item',
            field=models.CharField(choices=[('--КУ Стартап--', 'КУ Стартап'), ('--КУ Бизнес--', 'КУ Бизнес'), ('--КУ Мероприятия--', 'КУ Мероприятия'), ('Покупка лидов', 'Покупка лидов'), ('Лендинг (шаблон)', 'Лендинг (шаблон)'), ('Лендинг (уникальный)', 'Лендинг (уникальный)'), ('Ведение соцсетей', 'Ведение соцсетей'), ('Управление репутацией', 'Управление репутацией'), ('Другое', 'Другое')], max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post_name',
            field=models.CharField(choices=[('Менеджер по продажам', 'Менеджер по продажам'), ('Аккаунт-менеджер', 'Аккаунт-менеджер'), ('Младший маркетолог', 'Младший маркетолог'), ('Интернет-маркетолог', 'Интернет-маркетолог'), ('Колл-оператор', 'Колл-оператор'), ('РОА', 'РОА'), ('РОМ', 'РОМ'), ('Ассистент директора', 'Ассистент директора')], max_length=40),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
